version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: ./config/php/Dockerfile
    image: web-cake:5.4
    container_name: web
    ports:
      - 80:80
    volumes:
      - ..:/var/www/html/
      - ./config/php-custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./config/apache/cakephp.conf:/etc/apache2/sites-enabled/cakephp.conf
    networks:
      - internal
    restart: unless-stopped
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./data/mysql:/var/lib/mysql:delegated
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - internal
      - database
  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    environment:
      ADMINER_PLUGINS: tables-filter json-column table-indexes-structure
    ports:
      - 81:8080
    networks:
      - database
    restart: unless-stopped
    container_name: adminer
networks:
  database:
    external: true
  internal:
    driver: bridge
